### ISSUE TITLE
[linux][arch]: support Arch Linux

### ISSUE THREAD

**Issue by BaseMax** [github/gh-net#1]
Hi friends,
Are Arch-based Linux distributions supported?
https://archlinux.org/
https://github.com/github/gh-net#supported-platforms

**Comment by legomushroom** [comment]
hey @BaseMax 👋 Didn't specifically test it, but will try it out in a bit. Are you interested in the developer's machine support or the in-codesapce side (or both)?

**Comment by BaseMax** [comment]
Hey Oleg, Yes I would like to help If I can. @legomushroom

**Comment by BaseMax** [comment]
Let me know if I can help in any cases. You can mail or add me anywhere needed.

**Comment by BaseMax** [comment]
Also, My machine is Arch-based, and I am going to test it.

https://github.com/cli/cli/issues/1459#issuecomment-1097114362

```
$ gh extension install github/gh-net
✓ Installed extension github/gh-net
```

```
$ gh extension upgrade github/gh-net
✓ Extension already up to date
```

```
$ sudo gh net start
[sudo] password for max: 
unknown command "net" for "gh"

Usage:  gh <command> <subcommand> [flags]

Available commands:
  alias
  api
  auth
  browse
  codespace
  completion
  config
  extension
  gist
  gpg-key
  help
  issue
  pr
  release
  repo
  run
  secret
  ssh-key
  workflow
```

```
$ gh net start

  ⚠️ This command requires root privileges to bind to network sockets.
```

**Comment by legomushroom** [comment]
@BaseMax seems like you need to install the extension as root to be able to use with sudo as GH CLI installs it in different per-user locations 🤔 Still looking into it.

Help me to understand your case, what is your developer machine platform and what platform you are trying to connect to? Are they both alpines?

Alpine generally works but it definitely has few hiccups (this is Alpine Codespace with MacOSx client):

![image](https://user-images.githubusercontent.com/1478800/163041052-693183fc-8957-42ad-9371-2c4a1bb2a0b8.png)

- [ ] need to streamline the user permissions
- [ ] sort out automatic `gh cli` installation
- [ ] script to update `gh net` extension exits with (1)

**Comment by BaseMax** [comment]
> Help me to understand your case...

I just installed `github/gh-net` and that was installed successfully.
But `sudo gh net start` does not works.

```
$ sudo gh net start
[sudo] password for max: 
unknown command "net" for "gh"
```

What is wrong with my command?

**Comment by legomushroom** [comment]
@BaseMax `sudo` command uses the `root` user while non-sudo uses whatever other user you have. GH CLI installs extension in user folder hence you have to install the extension with sudo like this: `sudo gh extension install github/gh-net`

**Comment by BaseMax** [comment]
Thanks, Now installed as ROOT.

```
$ sudo gh extension install github/gh-net
✓ Installed extension github/gh-net
```

```
$ sudo gh net start
thread 'main' panicked at 'Failed to start VPN Gateway: No such file or directory (os error 2)', gh-extension/src/main.rs:15:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```


----

```
$ sudo RUST_BACKTRACE=1 gh net start
thread 'main' panicked at 'Failed to start VPN Gateway: No such file or directory (os error 2)', gh-extension/src/main.rs:15:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: tokio::park::thread::CachedParkThread::block_on
   5: tokio::runtime::thread_pool::ThreadPool::block_on
   6: gh_extension::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by BaseMax** [comment]
```
$ sudo RUST_BACKTRACE=full gh net start
[sudo] password for max: 
thread 'main' panicked at 'Failed to start VPN Gateway: No such file or directory (os error 2)', gh-extension/src/main.rs:15:18
stack backtrace:
   0:     0x7f12e64b683d - std::backtrace_rs::backtrace::libunwind::trace::h081201764674ef17
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f12e64b683d - std::backtrace_rs::backtrace::trace_unsynchronized::hebab37398c391bd7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f12e64b683d - std::sys_common::backtrace::_print_fmt::h301516df68ed24f9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f12e64b683d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f5170f4f03a12c0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f12e64f952c - core::fmt::write::h5dc5601e8d9f6367
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7f12e64ae3f8 - std::io::Write::write_fmt::h5b19302eb99d9acf
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7f12e64b8d17 - std::sys_common::backtrace::_print::hd81cf53a75c8ae6a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f12e64b8d17 - std::sys_common::backtrace::print::hb5aa882e87c2a0dc
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f12e64b8d17 - std::panicking::default_hook::{{closure}}::had913369af61b326
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7f12e64b89e0 - std::panicking::default_hook::h37b06af9ee965447
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7f12e64b9469 - std::panicking::rust_panic_with_hook::hf2019958d21362cc
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x7f12e64b9157 - std::panicking::begin_panic_handler::{{closure}}::he9c06fdd592f8785
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:     0x7f12e64b6d04 - std::sys_common::backtrace::__rust_end_short_backtrace::ha521b96560789310
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7f12e64b8e69 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x7f12e615f123 - core::panicking::panic_fmt::h28f1697d4e9394b4
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x7f12e615f213 - core::result::unwrap_failed::hea43ef43a7a8c801
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
  16:     0x7f12e6201473 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha4ede1cf28dbcb6e
  17:     0x7f12e6210478 - tokio::park::thread::CachedParkThread::block_on::h216294dca6476c50
  18:     0x7f12e62123c7 - tokio::runtime::thread_pool::ThreadPool::block_on::h4d5852db3944296d
  19:     0x7f12e61a85b0 - gh_extension::main::h86a97264e7cf402c
  20:     0x7f12e62112b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc465e590447b7032
  21:     0x7f12e61add99 - std::rt::lang_start::{{closure}}::hf37b5690501fe698
  22:     0x7f12e64b5f94 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd127f27863548251
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  23:     0x7f12e64b5f94 - std::panicking::try::do_call::h926290883a1d024e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  24:     0x7f12e64b5f94 - std::panicking::try::hc74a3d1f4a4b6e5f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  25:     0x7f12e64b5f94 - std::panic::catch_unwind::h5eb7ded2df1a4d5f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  26:     0x7f12e64b5f94 - std::rt::lang_start_internal::{{closure}}::h0736f9682f7c55ea
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  27:     0x7f12e64b5f94 - std::panicking::try::do_call::h2772c479b1c89ef7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  28:     0x7f12e64b5f94 - std::panicking::try::h967ebbc371287391
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  29:     0x7f12e64b5f94 - std::panic::catch_unwind::h41bcc02b28316856
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  30:     0x7f12e64b5f94 - std::rt::lang_start_internal::haf46799f55774d07
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  31:     0x7f12e61aec92 - main
```

**Comment by legomushroom** [comment]
Tested `Arch Linux` inside Codespace, - works great 👍 Didn't test it on the `local` machine yet 🤞

Note that the tool depends on `SSH` and GitHub CLI to be able to connect hence a Codespace must have those tools installed. Sample docker file for those dependencies:

```Dockerfile
FROM archlinux:latest
USER root

RUN echo "y" | pacman -S sudo && \
    echo "y" | sudo pacman -S github-cli

RUN echo "y" | sudo pacman -S openssh && \
    sudo groupadd -f ssh && \
    sudo groupadd -f sshd && \
    sudo usermod -a -G ssh,sshd root
```

I'll create a separate issue to track `local` machine support for Arch Linux 📘
